[build]
  command = "npx expo export -p web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  EXPO_USE_FAST_RESOLVER = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200